- name: vps base config
  hosts: boxemanvps1
  become: true
  gather_facts: true
  roles:
    - { role: ansible.motd , tags: ['common'] }
    - { role: ansible-resolv, tags: ['common'] }
    - { role: ansible.pkg_config , tags: ['common'] }
    - { role: ansible.sshd , tags: ['common'] }
  tasks:
    - include: common.yml
      tags: [ 'common' ]

- name: vps additional config
  hosts: boxemanvps1
  become: true
  gather_facts: true
  roles:
    - { role: ansible.openvpn , openvpn_instance: "{{ openvpn_instance_home}}" , openvpn_instance_name: home , tags: [ 'openvpn' ]}
    - { role: ansible.openvpn , openvpn_instance: "{{ openvpn_instance_warrior}}" , openvpn_instance_name: warrior , tags: [ 'openvpn' ]}
    - { role: ansible.transmission , tags: [ 'transmission' ] }
  tasks:
    - include: openvpn_client.yml  
      tags: [ 'openvpn' ]

    - include: letsencrypt.yml
      tags: [ 'letsencrypt' ]

    - include: httpd.yml
      tags: [ 'httpd' ]

    - include: nfs.yml
      tags: ['nfs']
    
    - include: openup.yml
      tags: ['openup']    
